export const type = {
    FETCH_WEATHER_FORECAST: "FETCH_WEATHER_FORECAST",
    REQUEST_WEATHER_FORECAST: "REQUEST_WEATHER_FORECAST",
    FAILED_WEATHER_FORECAST: "FAILED_WEATHER_FORECAST",
    FETCH_CURRENT_WEATHER: "FETCH_CURRENT_WEATHER",
    REQUEST_CURRENT_WEATHER: "REQUEST_CURRENT_WEATHER",
    FAILED_CURRENT_WEATHER: "FAILED_CURRENT_WEATHER"
};